### PR TITLE
Refactored Hash’s deep_symbolize! method to be able to symbolise nest…

### PR DESCRIPTION
**Pull request by rybex**
…ed array of hashes to keep consistency

### CODE REVIEW

**Comment by mereghost** [comment]
@rybex could you fix the rubocop warnings so it does not break the CI checks. =)

**Comment by rybex** [comment]
@mereghost My bad. Fixed ;)

**Comment by cllns** [comment]
Should we check for `is_a?(Array)`, or could we do `.respond_to?(:each)`, to see if it's Enumerable?

This would have a benefit of working on other Enumerable objects, like a `Set` of strings would symbolize the contents of the set.

Just a thought, there might be a good reason we don't want to do this. Hash-like objects are enumerable, but they're checked first, so we don't have to worry about them.

**Comment by jodosha** [comment]
@rybex Thanks for this PR, but this can't be merged.

You changed the behavior of `Hanami::Utils::Hash#deep_symbolize!` (instance method), but you tested the behavior of `Hanami::Utils::Hash.deep_symbolize` (class method).

If you revert your changes to `lib/hanami/utils/hash.rb` the spec will pass. That means, the class method is already able to provide the behavior you are looking for.

Also, we're migrating away from the instance methods of `Hanami::Utils::Hash`.

I'm closing this, and I encourage you to use the class method instead. Thank you.

**Pull request closed without merging**
