### PR TITLE
Replace period in underscored string

### PR DESCRIPTION
**Pull request by tak1n**
Related to https://github.com/hanami/hanami/issues/1163

### CODE REVIEW

**Comment by tak1n** [comment]
Should I open a separate PR against `main` as it still seems to use the same `underscore` method as well?

**Comment by adam12** [comment]
The fix looks good, but I am not sure how to approach this because it is backwards breaking behaviour. Probably best to let @jodosha look at it when he has a free moment.

**Review by jodosha — CHANGES_REQUESTED** [review]
@tak1n Please take also care of the [instance level interface](https://github.com/hanami/utils/blob/0ff863325b9c0f6a003d2125683cd74708aa7ea5/lib/hanami/utils/string.rb#L488).

**Comment by tak1n** [comment]
> @tak1n Please take also care of the [instance level interface](https://github.com/hanami/utils/blob/0ff863325b9c0f6a003d2125683cd74708aa7ea5/lib/hanami/utils/string.rb#L488).

Done

**Review by jodosha — APPROVED** [review]
@tak1n Thank you! 👍

**Pull request merged**
