### PR TITLE
Add missing tests for Kernel#numeric? method

### PR DESCRIPTION
**Pull request by davydovanton**
Reference https://github.com/hanami/utils/commit/57f6be767b917ff494476c25332e7cae501d904d

/cc @hanami/contributors @hanami/core-team

### CODE REVIEW

**Comment by jodosha** [comment]
@davydovanton Hey, thanks for these additional tests. This method is indirectly tested via `.Integer` and `.Float`, which use it.

I don't mind to add extra tests for it, since now it's used outside of this library. This PR helped me to spot one behavior to fix: the method doesn't return a boolean result. It returns `nil`, instead of `false` and `MatchData` instance instead of `true`.

Can you please make sure that it will work as expected? Thank you very much.

**Comment by davydovanton** [comment]
@jodosha YES! When I wrote tests I asked myself why this method return numeric value. I can fix this, but I think that this changes make method more slow.

**Comment by jodosha** [comment]
@davydovanton You're right. The difference isn't huge for MRI 2.2, 2.3, but it is for JRuby 9k. See this benchmark: https://gist.github.com/jodosha/db1cf2696e6a4b84a95a7ab4853c5a92

**Comment by davydovanton** [comment]
hm, interesting results. I was hoping that the result would be worse 😕
I think that this difference is very small that's why I prefer select more idiomatically alternative.

**Comment by davydovanton** [comment]
@jodosha done

**Comment by jodosha** [comment]
@davydovanton Thank you, merged!

**Comment by davydovanton** [comment]
Thanks for merge :+1:

**Pull request merged**
