### PR TITLE
removed duplicable and modified with object#dup

### PR DESCRIPTION
**Pull request by pawan92**
Initial attempt

### CODE REVIEW

**Comment by pawan92** [comment]
thanks for the tips. ill take another crack at it!

**Comment by pawan92** [comment]
Updated. Not sure if i did it correctly.  please let me know

**Comment by jodosha** [comment]
@pawan92 Thanks for the follow up. But you haven't addressed my points yet. Could you please try to do? Thanks.

**Comment by jodosha** [comment]
@pawan92 Thanks for this PR. Closing in favor of https://github.com/hanami/utils/pull/322

**Pull request closed without merging**
