### PR TITLE
Deprecate Utils::String instance methods

### PR DESCRIPTION
**Pull request by marionschleifer**
Ref https://github.com/hanami/utils/issues/259

### CODE REVIEW

**Comment by AlfonsoUceda** [comment]
Hi @marionschleifer can you implement changes requested by @jodosha?

**Comment by marionschleifer** [comment]
@AlfonsoUceda @jodosha I've been on holidays since the beginning of May and I will return on the 23rd of May. I will implement the changes as soon as I get back.

**Comment by AlfonsoUceda** [comment]
@marionschleifer any chance to work on this?

**Comment by jodosha** [comment]
I'm gonna finalize this work.

**Pull request merged**
