### PR TITLE
Hanami::Utils::Hash#symbolize! now handles array

### PR DESCRIPTION
**Pull request by lucasallan**
Fixes https://github.com/hanami/hanami/issues/653

### CODE REVIEW

**Comment by cllns** [comment]
Should we see if it's Enumerable rather than seeing if it's an Array?

**Comment by jodosha** [comment]
@lucasallan Thanks for this PR. I cleaned up a bit, according to the changes introduced by #162

**Comment by jodosha** [comment]
@cllns The implementation now uses `Enumerable` instead of `Array`.

**Comment by jodosha** [comment]
I had to revert this and remove from the release because it breaks `Hanami::Entity`. https://travis-ci.org/hanami/model/builds/185408316

Ref 3f8ebf8

**Pull request merged**
