### PR TITLE
Remove Inflector and String#pluralize String#singularize methods

### LINKED ISSUE #267: Remove `Utils::Inflector` and `Utils::String.pluralize` / `.singularize`
From 2.0 Hanami will use `dry-inflector` instead of `Utils::Inflector`.

  - [ ] Remove `Utils::Inflector`
  - [ ] Remove `Utils::String.pluralize` and `.singularize`

---

This change **MUST** go to `unstable` branch of this repository.

---

Ref https://trello.com/c/nJhd5awo

### PR DESCRIPTION
**Pull request by artofhuman**
Closes #267

### CODE REVIEW

**Comment by jodosha** [comment]
@artofhuman Thanks for this PR. Before to merge this one, I'll wait for the following tasks first:

  * https://github.com/hanami/model/issues/481
  * https://github.com/hanami/hanami/issues/922

By merging this, without working on these ☝️ first, will cause build failure for `hanami-model` and `hanami` due to the removal of these methods.

**Comment by AlfonsoUceda** [comment]
All dependant issues has been merged, @artofhuman can you resolve conflicts so we can merge this PR? thank you so much.

**Comment by artofhuman** [comment]
@AlfonsoUceda done

**Comment by jodosha** [comment]
@artofhuman Hey thanks for this PR, but I had to close it in favor of https://github.com/hanami/utils/pull/319

**Pull request closed without merging**
