### PR TITLE
Do not mutate input hash when filter sensitive params

### PR DESCRIPTION
**Pull request by hieuk09**
Currently, if I logs `params` in controller before processing, and use `filter` option for `Hanami::Logger`, then any sensitive information will be mutated to `[FILTERED]`.

### CODE REVIEW

**Comment by hieuk09** [comment]
Hi @jodosha, the CI is currently failing because of this check

```
hanami-utils.gemspec:19:32:  C: Gemspec/RequiredRubyVersion: required_ruby_version (2.3, declared in  hanami-utils.gemspec) and TargetRubyVersion (2.4, which may be  specified in .rubocop.yml) should be equal.
--
```

Do you know how to fix this?

**Comment by jodosha** [comment]
@hieuk09 I'm gonna to take care of it as it goes beyond the scope of this PR.

**Comment by jodosha** [comment]
@hieuk09 I've fixed master build. Could you please rebase and push the changes here? That should fix the build here. Thanks for your patience.

**Comment by hieuk09** [comment]
@jodosha thank you, I rebased the branch

**Review by jodosha — APPROVED** [review]

**Pull request merged**
