### PR TITLE
Add methods #successful? and #failing? to Interactor

### PR DESCRIPTION
**Pull request by mgrachev**
Example:
```
module Web::Controllers::Projects
  class Create
    include Web::Action

    params do
      param :project do
        param :name, presence: true
      end
    end

    def call(params)
      return unless params.valid?

      # Interactor
      create_project = CreateProject.new(params[:project]).call
      return if create_project.failure?

      redirect_to routes.projects_path
    end
  end
end
```

### CODE REVIEW

**Comment by joneslee85** [comment]
cc @hanami/core-team 

I am 👍 with this convenient method

**Comment by jodosha** [comment]
@mgrachev What about:

```ruby
return unless result.valid?
```

Which is similar to the line at the begin of the method:

```ruby
return unless params.valid?
```

**Comment by cllns** [comment]
I like this!

@jodosha Do you mean `return unless result.success?`

I prefer the implementation @mgrachev wrote. It will return `true/false` rather than `true/nil`. Any reason `true/nil` would be better?

**Comment by jodosha** [comment]
@cllns Yup, sorry there was a typo.

My suggestion is to make consistent how the guards are read in that method.

```ruby
def call(params)
    return unless params.valid?

    # Interactor
    create_project = CreateProject.new(params[:project]).call
    return unless create_project.success? # This is my suggestion: it's consistent with the first line of this method.

    redirect_to routes.projects_path
end
```

What do you think?

**Comment by cllns** [comment]
ah, I see. I thought you were saying `return unless create_project.success?` should be the body of the `failure?` mehod. 

Yea, that looks good in this case but I don't really have a preference either way. I think `.failure?` is a useful convenience method though, for people who use Interactors in a different way (like outside of an Action, for a non-web usage).

Honestly, I like to avoid `unless` whenever possible, so I'd prefer to write the first line as `return if params.invalid?` (if `params.invalid?` were implemented) :D

**Comment by jodosha** [comment]
@mgrachev @joneslee85 @cllns I have to confess that I don't like the original choice of `#success?` because it reads bad on tests.

Minitest:

```ruby
result.must_be :success?
```

RSpec:

```ruby
expect(result).to be_success
```

I think we should improve that. My proposal is:

  1. Define `#successful?` method
  2. Make `#success?` an alias of `#successful?` for backward compatibility
  3. Introduce `#failing?` (instead of `#failure?`) as opposite of `#successful?`

What do you think?

**Comment by joneslee85** [comment]
@jodosha I like that proposal, to me adjective `successful` is much better in grammar.

**Comment by jodosha** [comment]
Let's go for it! 😉

**Comment by mgrachev** [comment]
@jodosha Done.

**Comment by jodosha** [comment]
@mgrachev Thank you very much. Merging it!

**Pull request merged**
