### PR TITLE
Small refactor

### PR DESCRIPTION
**Pull request by ilasorsa**

### CODE REVIEW

**Comment by jodosha** [comment]
@ilasorsa Hey Ivan, thanks for this refactoring. The build fails for a reason that's not concerning your change. Can you please merge `master` in your branch and push again? Thanks should fix the build for your PR. Thanks!

**Comment by ilasorsa** [comment]
@jodosha I started my branch from master, there are no changes. Should I refork the repo?

**Comment by jodosha** [comment]
@ilasorsa Make sure that 701513e43434dbfd0fc15250bd5cf2bbaae6a627 and af6cb534ec868c4414a81c915359f5862add07c7 are included in your upstream.

You can do:

```bash
git remote add hanami https://github.com/hanami/utils.git
git pull hanami master
```

**Comment by jodosha** [comment]
@ilasorsa Thank you! Merging it!

**Pull request merged**
